name: Build-and-push
on: push

jobs:
  object-service-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MINDWM_TOKEN }}

      - name: Build and Push object-service
        run: |
          docker build -t ghcr.io/mindwm/vector-image/vector-image:latest .
          docker push ghcr.io/mindwm/vector-image/vector-image:latest
